// 2026-fall Week 6
const fall2026Week6Data = [
    {
        word: 'release',
        zh: '釋放；放開',
        pos: '(v.)',
        def: 'to set free; to let go',
        ex: '1. Release the bird! Let it go back to nature.<br>2. We released the tiger into the jungle.',
        category: 'Reading',
    },
    {
        word: 'take a shower',
        zh: '洗澡（淋浴）',
        pos: '(ph.) (v.)',
        def: 'to clean your body with running water',
        ex: '1. My dad likes to sing when he takes a shower.<br>2. You are so smelly! Go take a shower!',
        category: 'Reading',
    },
    {
        word: 'pajamas',
        zh: '睡衣',
        pos: '(n.)',
        def: 'the clothes people wear when they sleep (pajamas)',
        ex: '1. I am wearing my favorite pajamas.<br>2. My mother bought new pink pajamas for me.',
        category: 'Reading',
    },
    {
        word: 'ambulance',
        zh: '救護車',
        pos: '(n.)',
        def: 'a van for carrying sick people to the hospital',
        ex: '1. The old man was taken to the nearest hospital by ambulance.<br>2. The ambulance arrived at the accident scene quickly.',
        category: 'Reading',
    },
    {
        word: 'commotion',
        zh: '騷動；一陣喧鬧',
        pos: '(n.)',
        def: 'a sudden noise or excited movement',
        ex: '1. His arrival caused quite a commotion.<br>2. Becky was distracted by a commotion across the street.',
        category: 'Reading',
    },
    {
        word: 'crash',
        zh: '撞上；發生撞擊事故',
        pos: '(v.)',
        def: 'to hit and have a sudden and noisy accident',
        ex: '1. There was a car accident. The car crashed into a tree.<br>2. A dog ran on the path suddenly and caused John to crash his bike into the fence.',
        category: 'Reading',
    },
    {
        word: 'borrow',
        zh: '借（借進來，之後要還）',
        pos: '(v.)',
        def: 'to get or receive something from someone with the intention of giving it back after a period of time',
        ex: '1. My brother always borrows many books from the library.<br>2. I want to borrow a Chinese dictionary.',
        category: 'Reading',
    },
    {
        word: 'adaptation',
        zh: '適應（幫助動物活下去的身體構造或行為）',
        pos: '(n.)',
        def: 'a body part or a way an animal acts that helps it stay alive',
        ex: '1. An adaptation is a change to fit the environment.<br>2. Animals have special adaptations to survive.',
        category: 'Science',
    },
    {
        word: 'camouflage',
        zh: '偽裝；保護色',
        pos: '(n.)',
        def: 'a way that animals blend into their surroundings',
        ex: '1. Animals use camouflage to stay safe.<br>2. Camouflage allows animals to hide from predators.',
        category: 'Science',
    },
    {
        word: 'enemy',
        zh: '敵人（複數 enemies）',
        pos: '(n.)',
        def: 'someone who hates you and wants to harm you (enemies)',
        ex: '1. Cats and dogs are natural enemies.<br>2. Don\'t make an enemy of your classmates. You should get along well with them.',
        category: 'Science',
    },
];
