// 2026-fall Week 5
const fall2026Week5Data = [
    {
        word: 'deliver',
        zh: '遞送；把東西送到',
        pos: '(v.)',
        def: 'to take goods, letters, etc. to people\'s houses or places of work',
        ex: '1. The mailman delivers letters to everybody\'s mailbox.<br>2. We ordered a sofa from the store and the clerk will deliver it for us.',
        category: 'Reading',
    },
    {
        word: 'vote',
        zh: '投票；表決',
        pos: '(v.)',
        def: 'people in a group decide something by making choices',
        ex: '1. We voted on whether to see the movie or watch TV tonight.<br>2. We need a class leader. Let\'s vote!',
        category: 'Reading',
    },
    {
        word: 'flush',
        zh: '沖水（用大量的水沖乾淨）',
        pos: '(v.)',
        def: 'to clean something by letting a lot of water run through it',
        ex: '1. You must flush the toilet before you leave.<br>2. He put tissues in the toilet and flushed them away.',
        category: 'Reading',
    },
    {
        word: 'bounce',
        zh: '彈跳；反彈',
        pos: '(v.)',
        def: 'move up after hitting a surface',
        ex: '1. Mike loves to bounce the basketball.<br>2. The children love bouncing on the soft bed.',
        category: 'Reading',
    },
    {
        word: 'hospital',
        zh: '醫院',
        pos: '(n.)',
        def: 'a building for sick people to get better',
        ex: '1. When I am sick, I go to the hospital.<br>2. There are many doctors and nurses in the hospital.',
        category: 'Reading',
    },
    {
        word: 'except',
        zh: '除了……之外',
        pos: '(prep.)',
        def: 'not including',
        ex: '1. They all went to sleep except the young man.<br>2. I go to school every day except weekends.',
        category: 'Reading',
    },
    {
        word: 'prepare',
        zh: '準備',
        pos: '(v.)',
        def: 'to get ready',
        ex: '1. Kevin prepared some pencils and an eraser for his quiz.<br>2. My mom prepares vegetables and fish for dinner.',
        category: 'Reading',
    },
    {
        word: 'larva',
        zh: '幼蟲（複數 larvae）',
        pos: '(n.)',
        def: 'the worm-like young of an insect (plural → larvae)',
        ex: '1. There is a larva on the leaf.<br>2. A caterpillar is the larva of a butterfly.',
        category: 'Science',
    },
    {
        word: 'pupa',
        zh: '蛹（複數 pupae）',
        pos: '(n.)',
        def: 'a larva spins a hard case around itself (plural → pupae)',
        ex: '1. Inside the hard case, the pupa changes into a butterfly.<br>2. When a caterpillar makes a hard case, it is called a pupa.',
        category: 'Science',
    },
    {
        word: 'adult',
        zh: '成蟲；完全長大的個體',
        pos: '(n.)',
        def: 'a fully grown person or animal',
        ex: '1. An adult butterfly looks different from a larva.<br>2. Children may watch this movie with adults.',
        category: 'Science',
    },
];
