// 2026-fall Week 3
const fall2026Week3Data = [
    {
        word: 'imitation',
        zh: '模仿；仿效',
        pos: '(n.)',
        def: 'an action of copying someone or something as a model',
        ex: '1. Children learn to speak by imitation.<br>2. She can do a wonderful imitation of a bird\'s song.',
        category: 'Reading',
    },
    {
        word: 'spread',
        zh: '攤開；把東西分開',
        pos: '(v.)',
        def: 'to move things apart',
        ex: '1. My brother spread his toys everywhere in the living room.<br>2. He spreads the cards out on the table.',
        category: 'Reading',
    },
    {
        word: 'slurp',
        zh: '出聲地吸食（稀哩呼嚕地喝）',
        pos: '(v.)',
        def: 'to eat or drink in a noisy way by sucking with your lips',
        ex: '1. The hungry girl is slurping her noodles loudly.<br>2. It is noisy and not polite to slurp your soup.',
        category: 'Reading',
    },
    {
        word: 'noise',
        zh: '噪音；吵鬧聲',
        pos: '(n.)',
        def: 'a loud sound',
        ex: '1. What\'s up? There\'s such a loud noise in the room.<br>2. Don\'t make so much noise; the baby is sleeping.',
        category: 'Reading',
    },
    {
        word: 'surprise',
        zh: '驚訝；意外的感覺',
        pos: '(n.)',
        def: 'the feeling caused by something unexpected',
        ex: '1. We are going to give Jessie a surprise birthday party.<br>2. It was a great surprise to meet my old friend.',
        category: 'Reading',
    },
    {
        word: 'mess',
        zh: '髒亂；一團亂',
        pos: '(n.)',
        def: 'something is untidy or looks dirty',
        ex: '1. My brother always makes a big mess in his room.<br>2. The living room was a mess after the party.',
        category: 'Reading',
    },
    {
        word: 'crate',
        zh: '木箱；板條箱',
        pos: '(n.)',
        def: 'a large wooden box, especially for packing things',
        ex: '1. Please put your toys in the crate.<br>2. A puppy jumped out of the crate.',
        category: 'Reading',
    },
    {
        word: 'trait',
        zh: '特徵（生物長相上的特點）',
        pos: '(n.)',
        def: 'the way a living thing looks',
        ex: '1. The color of a flower is a trait.<br>2. What are some traits of a polar bear?',
        category: 'Science',
    },
    {
        word: 'survive',
        zh: '存活；活下來',
        pos: '(v.)',
        def: 'to stay alive',
        ex: '1. Many people died in the earthquake, but he survived.<br>2. Animals can\'t survive without water.',
        category: 'Science',
    },
    {
        word: 'petal',
        zh: '花瓣',
        pos: '(n.)',
        def: 'one of the colorful parts of a flower that is leaf shaped',
        ex: '1. A rose has many petals.<br>2. My sister picked up some petals in the garden.',
        category: 'Science',
    },
];
