// 2026-fall Week 4
const fall2026Week4Data = [
    {
        word: 'protect',
        zh: '保護',
        pos: '(v.)',
        def: 'to keep safe',
        ex: '1. I protect myself against the sun with a beach umbrella.<br>2. Parents always protect their children from danger.',
        category: 'Reading',
    },
    {
        word: 'special',
        zh: '特別的；不一樣的',
        pos: '(adj.)',
        def: 'of a particular kind; not usual',
        ex: '1. Today is a special day. It’s Fiona’s birthday.<br>2. Everybody is special in their own way.',
        category: 'Reading',
    },
    {
        word: 'stretchy',
        zh: '有彈性的；可以拉長的',
        pos: '(adj.)',
        def: 'easily be made longer or wider without tearing or breaking',
        ex: '1. The rubber band is stretchy.<br>2. You can use the stretchy clay to make different shapes.',
        category: 'Reading',
    },
    {
        word: 'ceiling',
        zh: '天花板',
        pos: '(n.)',
        def: 'the top of a room',
        ex: '1. The lights and fans in this room are on the ceiling.<br>2. Look! There are cracks in the walls and ceiling.',
        category: 'Reading',
    },
    {
        word: 'think',
        zh: '想；思考（過去式 thought）',
        pos: '(v.)',
        def: 'to use the mind to form ideas and opinions (thought)',
        ex: '1. I can’t think of an answer. Could you help me?<br>2. Miss Brown thought long and hard before coming to a decision.',
        category: 'Reading',
    },
    {
        word: 'scary',
        zh: '可怕的；嚇人的',
        pos: '(adj.)',
        def: 'frightening; make you feel scared',
        ex: '1. This story is really scary. I am afraid to sleep alone.<br>2. This is a scary picture. I don’t like it.',
        category: 'Reading',
    },
    {
        word: 'without',
        zh: '沒有；不帶著',
        pos: '(prep.)',
        def: 'not having',
        ex: '1. The man entered the room without knocking on the door.<br>2. I drink my coffee without sugar.',
        category: 'Reading',
    },
    {
        word: 'reptile',
        zh: '爬蟲類（皮膚粗糙有鱗片）',
        pos: '(n.)',
        def: 'an animal with rough, scaly skin',
        ex: '1. Snakes, lizards, turtles, and crocodiles are reptiles.<br>2. The biggest reptile is the saltwater crocodile.',
        category: 'Science',
    },
    {
        word: 'amphibian',
        zh: '兩棲類（水陸都能生活）',
        pos: '(n.)',
        def: 'an animal that can live in both water and on land',
        ex: '1. Frogs, toads and newts are amphibians.<br>2. Amphibians can live in both water and on land.',
        category: 'Science',
    },
    {
        word: 'mammal',
        zh: '哺乳類（用奶餵小寶寶）',
        pos: '(n.)',
        def: 'an animal that feeds milk to its young',
        ex: '1. Female mammals make milk for their babies.<br>2. Mammals breathe through their lungs.',
        category: 'Science',
    },
];
