// 2026-fall Week 1
const fall2026Week1Data = [
    {
        word: 'cupboard',
        zh: '碗櫃；餐具櫃',
        pos: '(n.)',
        def: 'a piece of furniture with doors where plates, food, etc., can be stored',
        ex: '1. I help my mom put food in the cupboard.<br>2. We keep our dishes in the cupboard.',
        category: 'Reading',
    },
    {
        word: 'vegetable',
        zh: '蔬菜',
        pos: '(n.)',
        def: 'a part of a plant that you can eat',
        ex: '1. Farmers grow lots of vegetables on the farm.<br>2. I like vegetables because they are healthy.',
        category: 'Reading',
    },
    {
        word: 'go shopping',
        zh: '去買東西；去逛街購物',
        pos: '(ph.) (v.)',
        def: 'to go looking for things to buy',
        ex: '1. Mom likes to go shopping at the supermarket.<br>2. I went shopping for some new clothes last Saturday.',
        category: 'Reading',
    },
    {
        word: 'dairy',
        zh: '乳製品（牛奶做的食物）',
        pos: '(n.)',
        def: 'food made with milk, such as cream, butter, or cheese',
        ex: '1. Dragon bought some butter from the dairy group.<br>2. Milk and yogurt are dairy products.',
        category: 'Reading',
    },
    {
        word: 'balanced diet',
        zh: '均衡飲食',
        pos: '(n.)',
        def: 'a way of eating from the five food groups (meat, dairy, vegetable, fruit, bread) evenly',
        ex: '1. Danny doesn\'t have a balanced diet because he doesn\'t eat vegetables.<br>2. If you have a balanced diet, you can stay healthy.',
        category: 'Reading',
    },
    {
        word: 'doughnut',
        zh: '甜甜圈',
        pos: '(n.)',
        def: 'a small ring-shaped cake',
        ex: '1. My favorite dessert is chocolate doughnuts.<br>2. I had two doughnuts as a snack this afternoon.',
        category: 'Reading',
    },
    {
        word: 'burp',
        zh: '打嗝',
        pos: '(v.)',
        def: 'to pass gas noisily from the stomach through the mouth',
        ex: '1. Don\'t burp in class. It\'s not polite.<br>2. After Danny ate a lot of food, he burped loudly.',
        category: 'Reading',
    },
    {
        word: 'breathe',
        zh: '呼吸',
        pos: '(v.)',
        def: 'to take air into the lungs and let it out again',
        ex: '1. It\'s great to breathe the fresh air in the forest.<br>2. All mammals breathe air.',
        category: 'Science',
    },
    {
        word: 'oxygen',
        zh: '氧氣',
        pos: '(n.)',
        def: 'a gas made by plants that is found in the air we breathe',
        ex: '1. A whale needs to breathe oxygen to live.<br>2. Oxygen is a gas that you can\'t see, taste, or smell.',
        category: 'Science',
    },
    {
        word: 'mineral',
        zh: '礦物質',
        pos: '(n.)',
        def: 'a bit of rock and soil that helps plants and animals grow',
        ex: '1. Plants use minerals in the soil to stay healthy.<br>2. Plants can get minerals from the soil.',
        category: 'Science',
    },
];
