// 2026-fall Week 7
const fall2026Week7Data = [
    {
        word: 'camping',
        zh: '露營',
        pos: '(n.)',
        def: 'sleeping in tents in the outdoors',
        ex: '1. My parents and I go camping in the mountains.<br>2. We\'ll prepare many things for camping this weekend.',
        category: 'Reading',
    },
    {
        word: 'shake',
        zh: '搖動；抖動（過去式 shook）',
        pos: '(v.)',
        def: 'to move up and down with short, quick movement (shook)',
        ex: '1. She smiled at the person and shook her hand.<br>2. I like to shake my puppy\'s paw because it is my best friend.',
        category: 'Reading',
    },
    {
        word: 'yawn',
        zh: '哈欠',
        pos: '(n.)',
        def: 'an act of opening the mouth wide and take in air usually when tired or bored',
        ex: '1. Her eyes watered when she tried to stop a yawn.<br>2. Mudge gave a big, slow, loud yawn. (P.129)',
        category: 'Reading',
    },
    {
        word: 'shiver',
        zh: '發抖（因為冷或害怕）',
        pos: '(v.)',
        def: 'to shake with cold or fear',
        ex: '1. I shiver because the weather is too cold.<br>2. After drinking a cup of hot tea, she stopped shivering.',
        category: 'Reading',
    },
    {
        word: 'drool',
        zh: '流口水',
        pos: '(v.)',
        def: 'to let saliva flow out of the mouth',
        ex: '1. Henry drooled when he saw those delicious doughnuts.<br>2. Amy cannot stop drooling when she is napping.',
        category: 'Reading',
    },
    {
        word: 'giggle',
        zh: '咯咯笑；偷偷地笑',
        pos: '(v.)',
        def: 'to laugh repeatedly but quietly',
        ex: '1. He giggled like a little kid.<br>2. She giggled when her teacher told a joke.',
        category: 'Reading',
    },
    {
        word: 'slippery',
        zh: '滑的；濕滑的',
        pos: '(adj.)',
        def: 'wet or smooth so that it\'s very hard to stand on',
        ex: '1. Cindy knocked over her soup, so the floor was slippery.<br>2. Ice made the road too slippery to drive on.',
        category: 'Reading',
    },
    {
        word: 'grassy',
        zh: '長滿草的',
        pos: '(adj.)',
        def: 'covered with grass',
        ex: '1. My grandmother\'s backyard is grassy.<br>2. We slid down the grassy slope.',
        category: 'Science',
    },
    {
        word: 'habitat',
        zh: '棲地；棲息地',
        pos: '(n.)',
        def: 'a place where animals or plants can get everything they need to live',
        ex: '1. Animals live and grow in their own habitats.<br>2. A habitat has everything a plant or animal needs.',
        category: 'Science',
    },
    {
        word: 'shelter',
        zh: '遮蔽處；躲避危險或壞天氣的地方',
        pos: '(n.)',
        def: 'protection from danger or bad weather',
        ex: '1. You should keep your new bike under shelter.<br>2. Bears find shelter in a hole or cave.',
        category: 'Science',
    },
];
