// 2026-fall Week 2
const fall2026Week2Data = [
    {
        word: 'kitchen',
        zh: '廚房',
        pos: '(n.)',
        def: 'a room where people keep and cook food',
        ex: '1. Danny went to the kitchen and took some food.<br>2. She is washing dishes in the kitchen.',
        category: 'Reading',
    },
    {
        word: 'scratch',
        zh: '抓（癢）；搔',
        pos: '(v.)',
        def: 'to scrape or rub lightly, usually to stop itching',
        ex: '1. The boy laughed and scratched his head.<br>2. Dogs scratch their bodies with their paws.',
        category: 'Reading',
    },
    {
        word: 'parking lot',
        zh: '停車場',
        pos: '(n.)',
        def: 'a place to park cars',
        ex: '1. Maggie parked her new car in the parking lot.<br>2. There are many cars in the parking lot.',
        category: 'Reading',
    },
    {
        word: 'bare',
        zh: '光著的；空空的',
        pos: '(adj.)',
        def: 'not covered by clothes or empty',
        ex: '1. The cupboards are bare, I can\'t find anything to eat.<br>2. She had no socks or shoes on. She had bare feet.',
        category: 'Reading',
    },
    {
        word: 'roll',
        zh: '滾動；翻滾',
        pos: '(v.)',
        def: 'to move by turning over and over',
        ex: '1. He made the ball roll down the stairs.<br>2. The dog rolled on the grass.',
        category: 'Reading',
    },
    {
        word: 'excitement',
        zh: '興奮；激動',
        pos: '(n.)',
        def: 'the feeling of being excited',
        ex: '1. Robin\'s heart was pounding with excitement.<br>2. The children were jumping up and down with excitement.',
        category: 'Reading',
    },
    {
        word: 'crunch',
        zh: '喀滋喀滋地咬（硬或脆的東西）',
        pos: '(v.)',
        def: 'to chew something that is hard or crispy',
        ex: '1. I crunch ice cubes when it is hot.<br>2. The squirrel crunches nuts on the branch.',
        category: 'Reading',
    },
    {
        word: 'ripe',
        zh: '成熟的（可以吃了）',
        pos: '(adj.)',
        def: 'fully grown and ready to be eaten',
        ex: '1. The tomatoes aren\'t ripe.<br>2. When the fruit is ripe, it can be picked.',
        category: 'Science',
    },
    {
        word: 'seedling',
        zh: '幼苗；秧苗',
        pos: '(n.)',
        def: 'a young plant',
        ex: '1. Jack bought some seedlings and planted them in his garden.<br>2. How many seedlings are there in the greenhouse?',
        category: 'Science',
    },
    {
        word: 'pollen',
        zh: '花粉',
        pos: '(n.)',
        def: 'a sticky part inside a flower that helps make seeds',
        ex: '1. The insect carries the pollen from flower to flower.<br>2. The bee collects pollen and stores it.',
        category: 'Science',
    },
];
