// 2026-fall Week 8
const fall2026Week8Data = [
    {
        word: 'backpack',
        zh: '後背包',
        pos: '(n.)',
        def: 'a large bag that you carry on your back',
        ex: '1. I carry my backpack when I go mountain climbing.<br>2. Would you like to have an orange backpack?',
        category: 'Reading',
    },
    {
        word: 'cracker',
        zh: '鹹餅乾（脆脆的小餅乾）',
        pos: '(n.)',
        def: 'a small, salty and crunchy biscuit',
        ex: '1. My mom loves to eat crackers with cheese.<br>2. “What do you have in your pocket?” “I have a bag of crackers.”',
        category: 'Reading',
    },
    {
        word: 'lantern',
        zh: '提燈；燈籠',
        pos: '(n.)',
        def: 'a type of light that can be carried',
        ex: '1. My art teacher taught me how to make a paper lantern.<br>2. There is a jack-o-lantern made from a pumpkin.',
        category: 'Reading',
    },
    {
        word: 'snuggle',
        zh: '依偎；緊緊靠著',
        pos: '(v.)',
        def: 'to lie closely with someone or something and hold them',
        ex: '1. The mother snuggled with her baby.<br>2. The children snuggle together on the bed.',
        category: 'Reading',
    },
    {
        word: 'waterfall',
        zh: '瀑布',
        pos: '(n.)',
        def: 'water of a river or stream, falling straight down over cliffs',
        ex: '1. This mountain has beautiful waterfalls.<br>2. I see a rainbow by the waterfall.',
        category: 'Reading',
    },
    {
        word: 'unpack',
        zh: '把東西從包包或箱子裡拿出來',
        pos: '(v.)',
        def: 'to remove things from a bag, suitcase, or box',
        ex: '1. I don\'t have any time to unpack my bag.<br>2. I am unpacking my clothes.',
        category: 'Reading',
    },
    {
        word: 'pocket',
        zh: '口袋',
        pos: '(n.)',
        def: 'a small bag on the clothes for carrying things',
        ex: '1. Look! There are five pockets on my new pants.<br>2. I put a piece of paper into my pocket.',
        category: 'Reading',
    },
    {
        word: 'predator',
        zh: '掠食者（獵捕別的動物來吃）',
        pos: '(n.)',
        def: 'an animal that hunts other animals for food',
        ex: '1. Sharks are predators. They kill and eat other fish.<br>2. The predator hid behind the bush and waited to catch the deer.',
        category: 'Science',
    },
    {
        word: 'prey',
        zh: '獵物（被別的動物獵捕）',
        pos: '(n.)',
        def: 'an animal that is hunted by another animal',
        ex: '1. The cat wants to kill the bird, so the bird is the prey.<br>2. The lion is hunting for its prey.',
        category: 'Science',
    },
    {
        word: 'food chain',
        zh: '食物鏈',
        pos: '(n.)',
        def: 'the order of living things which need each other for food',
        ex: '1. People are at the top of the food chain.<br>2. In a food chain, each animal eats another living thing as food.',
        category: 'Science',
    },
];
