// 2026-spring Week 21
const spring2026Week21Data = [
    {
        word: 'went',
        pos: '(v.)',
        def: 'past simple of go',
        ex: '1. We went to school early this morning.<br>2. My mom went home late yesterday.',
        category: 'Reading',
    },
    {
        word: 'came',
        pos: '(v.)',
        def: 'past simple of come',
        ex: '1. The train slowly came to the station.<br>2. I came here to help you.',
        category: 'Reading',
    },
    {
        word: 'ran',
        pos: '(n.)',
        def: 'past simple of run',
        ex: '1. They ran over the grass.<br>2. He ran out the door.',
        category: 'Reading',
    },
    {
        word: 'slink',
        pos: '(v.)',
        def: 'to walk away from somewhere quietly so that you are not noticed',
        ex: '1. I tried to slink out of the room so that nobody would see me go.<br>2. He usually slinks off at about 3:30.',
        category: 'Reading',
    },
    {
        word: 'creek',
        pos: '(n.)',
        def: 'a narrow area of water that flows into the land from the sea, a lake, etc.',
        ex: '1. That night they set up camp near the creek.<br>2. There are often wild ducks swimming in the creek.',
        category: 'Reading',
    },
    {
        word: 'muddy',
        pos: '(adj.)',
        def: 'covered by or containing mud',
        ex: '1. Don\'t bring those muddy boots inside!<br>2. Take your shoes off outside if they are muddy.',
        category: 'Reading',
    },
    {
        word: 'was',
        pos: '(v.)',
        def: 'past simple of is and am',
        ex: '1. I was a teacher three years ago.<br>2. She was sick, so she was at home yesterday.',
        category: 'Reading',
    },
    {
        word: 'guess',
        pos: '(v.)',
        def: 'when you believe something is true or likely but are not certain',
        ex: '1. I guess I should start to prepare my final exam.<br>2. I\'m never going to guess the answer if you don\'t give me a clue.',
        category: 'Reading',
    },
    {
        word: 'vibrate',
        pos: '(v.)',
        def: 'to move back and forth',
        ex: '1. When an object stops vibrating, the sound stops too.<br>2. Whose phone is vibrating?',
        category: 'Science',
    },
    {
        word: 'pitch',
        pos: '(n.)',
        def: 'how high or low it is',
        ex: '1. Fast vibrations make sounds with a high pitch.<br>2. Slow vibrations make sounds with a low pitch.',
        category: 'Science',
    },
];
